language: node_js
sudo: required
node_js:
- "8"
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
before_install:
- openssl aes-256-cbc -K $encrypted_6ce2c3c94af0_key -iv $encrypted_6ce2c3c94af0_iv -in deployment.tar.enc -out deployment.tar -d
- tar xvf deployment.tar
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash > /dev/null; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- gcloud components install kubectl || true
install:
- cp ./deployment/conf/.env.js ./.env.js
- yarn install
- yarn add https://github.com/ninjadotorg/handshake-i18n
- yarn build
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./deployment/deploy.sh
  on:
    branch: develop
