language: node_js
sudo: required
node_js:
- "8"
branches:
  only:
    - develop
cache:
  yarn: true
  directories:
  - node_modules
  - "$HOME/google-cloud-sdk/"
before_install:
- openssl aes-256-cbc -K $encrypted_f1bc46c97fb9_key -iv $encrypted_f1bc46c97fb9_iv -in deployment.tar.enc -out deployment.tar -d
- tar xvf deployment.tar
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash > /dev/null; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud components install kubectl || true
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./deploy.sh
  on:
    branch: develop:
- provider: script
  skip_cleanup: true
  script: bash ./deploy2.sh
  on:
    branch: develop_coinbowl
