export default {
  HELLO: 'hello {name}',
  buy: 'Buy',
  sell: 'Sell',
  amount: 'amount',
  askUsingCreditCard: 'for {total} {fiatCurrency} using card?',
  change: 'Change',
  ccNumber: 'Number',
  ccExpire: 'Expiry',
  ccCVC: 'CVC',
  overCCLimit: 'Your limit is {currency}{limit}. You have already used {currency}{amount} ',

  required: 'Required',
  ccExpireTemplate: 'MM/YY',
  securityCode: '325',
  shakeNow: 'Shake',
  offerHandShakeContent: '{offerType} {amount} {currency} for {total} {currency_symbol} in {payment_method}?',
  offerHandShakeContentMe: '{offerType} {amount} {currency} for {total} {currency_symbol} ({payment_method})',
  offerHandShakeContentMeDone: '{offerType} {amount} {currency} for {total} {currency_symbol} ({payment_method})',
  instantOfferHandShakeContent: 'You{just}{offerType} {amount} {currency} for {total} {currency_symbol} on your card - fee {fee}%',
  offerDistanceContent: '{distanceKm} km ({distanceMiles} miles) away',
  transactonOfferInfo: 'Successful ({success}) / Failed ({failed})',
  createOfferConfirm: 'You are about to {type} {amount} {currency} for {total} {currency_symbol}',
  handshakeOfferConfirm: 'You are about to {type} {amount} {currency} for {total} {currency_symbol}',
  rejectOfferConfirm: 'Do you want to Reject this handshake? You will not be able to make transactions for 4 hours.',
  completeOfferConfirm: 'Do you want to Complete this handshake?',
  withdrawOfferConfirm: 'Do you want to Withdraw this handshake?',
  cancelOfferConfirm: 'Do you want to Cancel this handshake?',
  closeOfferConfirm: 'Do you want to Close this handshake?',
  acceptOfferConfirm: 'Do you want to Accept this handshake?',
  createOfferSuccessMessage: 'Create offer success',
  shakeOfferSuccessMessage: 'Shake offer success',
  closeOfferSuccessMessage: 'Close offer success',
  completeShakedfferSuccessMessage: 'Complete shaked offer success',
  cancelShakedfferSuccessMessage: 'Cancel shaked offer success',
  withdrawShakedfferSuccessMessage: 'Withdraw shaked offer success',
  buyUsingCreditCardSuccessMessge: 'Buy using Card success',
  notEnoughCoinInWallet: 'You only have {amount}({currency}) in default wallet {currency}. Fee ~ {fee}({currency}). Please add more',

  createOfferStoreConfirm: 'Do you want to create offer Buy {amountBuy} {currency} - Sell {amountSell} {currency}?',
  notEnoughCoinInWalletStores: 'You only have {amount}({currency}) in default wallet {currency}. Fee ~ {fee}({currency}). Please add more',
  addOfferItemSuccessMassage: 'Add offer item success',
  deleteOfferItemSuccessMassage: 'Delete offer item success',
  shakeOfferItemSuccessMassage: 'Shake offer item success',
  acceptOfferItemSuccessMassage: 'Accept offer item success',
  cancelOfferItemSuccessMassage: 'Cancel offer item success',
  rejectOfferItemSuccessMassage: 'Reject offer item success',
  completeOfferItemSuccessMassage: 'Complete offer item success',
  offerStoresAlreadyCreated: 'You have already create offer',
  offerStoreHandShakeContent: '{offerTypeBuy} {amountBuy} {currency} at {fiatAmountBuy} {fiatAmountCurrency}. {offerTypeSell} {amountSell} {currency} at {fiatAmountSell} {fiatAmountCurrency}',

  // FAQ
  FAQ_TITLE: 'FAQ',
  FAQ_HEADER_YELLOW: '',
  FAQ_HEADER: 'Décentralisé de prédiction change ',
  FAQ_DATA: [
    {
      question: 'quel est le Ninja PEX ?',
      answer: 'Ninja est un échange anonyme-to-peer décentralisé prédiction en cours d’exécution sur le dessus de l’Ethereum blockchain.',
    },
    {
      question: 'ce qui est spécial au sujet de PEX ? Pourquoi devrais je parie sur un ?',
      answer: 'Il permet aux parties de parier directement contre l’autre sans passer par une autorité centrale ou le bookmaker. Cela rend 100 % anonyme, pas de signes place aucun téléchargement requis. La gestion de Paris et au règlement des gains sont effectués collectivement par le réseau blockchain, protection des utilisateurs contre n’importe quel point de défaillance unique. Vous pouvez également créer vos propres marchés de prédiction.',
    },
    {
      question: 'ai-je besoin d’éther ? Supporte-t-il les autres cryptocurrencies ?',
      answer: 'Oui. Ninja accepte uniquement les ETH pour l’instant, mais le support sera ajouté pour les autres monnaies très bientôt.',
    },
    {
      question: ' Comment puis-je commencer avec Ninja ?',
      isList: true,
      answer: [
        {
          title: 'Obtenez l’éther :',
          content: 'Vous pouvez soit acheter ETH directement en PEX avec vos cartes de crédit ou d’échanges de pièces populaires tels que Coinbase ou Binance.',
        },
        {
          title: 'Recharger votre porte-monnaie PEX :',
          content: 'Transférer l’ETH dans le portefeuille PEX. Portefeuille de PEX est complètement décentralisé, la clé privée est tenue sur votre téléphone, que vous pouvez transférer et recevoir ETH.',
        },
        {
          title: 'Placer un pari :',
          content: 'Choix du marché vous voulez parier (p. ex. Brésil - Espagne), les résultats (c.-à-d. les victoires Brésil) et le site (c\'est-à-dire le support ou le pari contre l’issue)\n' +
          'Entrer dans le jeu vous voulez à pari (c.-à-d. 1 ETH) et les cotes (c.-à-d. 1 / 2,25)\n' +
          'Le moteur de Matching BEX trouverez alors une autre ordonnance qui parie contre vents et marées que vous définir.',
        },
        {
          title: 'Attendre le rapport :',
          content: 'Si vous gagnez, vos gains seront automatiquement transférées du contrat escrow intelligente à votre compte.',
        },
      ],
    },
    {
      question: 'puis-je créer mes propres cotes de préférés ? Comment ?',
      answer: 'Oui ! Lorsque vous créez votre propre pari, vous allez entrer dans l’événement qui que vous intéresse et le résultat que vous souhaitez parier sur. Ensuite, il suffit d’entrer votre mise et la cote souhaitée. Puis le moteur PEX ',
    },
    {
      question: 'Comment vous la police Paris douteux ou illégaux ?',
      answer: 'Nous construisons actuellement un système de freins et contrepoids à signaler les comportements inappropriés dans le dojo.',
    },
    {
      question: 'Comment est le système sait le résultat de Paris entre les gens ? Qui agit en tant qu’arbitre et vérifie un résultat par rapport à un autre à la conclusion du contrat ?',
      answer: 'Ninja aura bientôt une solution complètement décentralisée pour vérifier le résultat et motivant la vérité en disant (un DAO de reporters !). En attendant, que nous allons lancer juste à temps pour la Coupe du monde, notre équipe utilise ',
    },
    {
      question: 'où se déroule la pièce ?',
      answer: 'Personne ne détient les fonds. Tous les fonds sont conservés sécuritaire en dépôt jusqu\'à ce qu’une résolution soit atteinte.',
    },
    {
      question: 'Pourquoi devrais je parie sur blockchain au lieu d’utiliser les méthodes traditionnelles ?',
      answer: 'Un échange décentralisé de prédiction fournira vous la liberté de créer vos propres cotes et parier directement avec n’importe qui, vous offrons anonymat 100 % ninja et garantie des paiements.',
    },
    {
      question: 'qu’en est-il de la vie privée et anonymat ?',
      answer: 'Ninja nécessite aucun téléchargement et aucun signe d’ups. Cela veut dire aucun mot de passe, aucun numéro de téléphone et pas de courriels. anonymat 100 %.',
    },
    {
      question: ' dois-je payer tous les frais ?',
      answer: 'Il existe deux principaux types de frais : frais de créateur (pour le ninja qui crée le PARI) et les frais de réseau (un pourcentage de la taxe de créateur, qui se dirige vers le maintien de la plate-forme).',
    },
    {
      question: 'que dois-je faire quand le résultat est finalisé ?',
      answer: 'Rien. Si vous gagnez, vos gains seront automatiquement transférés sur votre compte. Si vous perdez, ce sera quelqu\'un d’autre compte.',
    },
    {
      question: 'où puis-je trouver une correspondance pour parier sur ?',
      answer: 'Sur la page d’accueil, vous serez en mesure de parcourir les marchés et les Paris en cours. Si vous ne trouvez pas que vous aimez, créez vos propres !',
    },
    {
      question: 'autres que sportives, je peux parier sur autre chose ? Comment ça marche ?',
      answer: 'Très bientôt, Ninja s’appliqueront à tout sous le soleil. La seule limite sera votre créativité. Vous pouvez facilement créer n’importe quel marché à n’importe quel événement futur, qu’elle soit sportive, politique, science, marchés, climat... vous l’appelez. ',
    },
    {
      question: 'ce qui va se passer à l’application mobile de la poignée de main ?',
      answer: 'Nous intégrerons Handshake (et vos fonctions préférées comme promesses, reconnaissances de dette, upload de contrat, etc.) dans le site Web mobile de Ninja. ',
    },
  ],

  // MobileOrTablet components
  MOT_TITLE: 'L’échange anonyme de quoi que ce soit',
  MOT_CONTENT_0: 'Le réseau de Ninja n’est accessible que via mobile',
  MOT_CONTENT_1: 'Ouvrez',
  MOT_CONTENT_2: 'dans votre navigateur mobile pour gagner l’entrée anonyme.',
  MOT_CONTENT_3: 'Aucun téléchargement nécessaire. Aucuns inscription ne nécessaire.',
  MOT_LIST_CONTENT: [
    {
      mainContent: 'Lisez le',
      placeHolderLink: 'livre blanc',
      link: 'https://medium.com/@ninjadotorg/shakeninja-bex-1c938f18b3e8',
      isBlankTarget: true,
    },
    {
      mainContent: 'Nous répondons à votre',
      placeHolderLink: 'FAQ',
      link: '/faq',
    },
    {
      mainContent: 'Rejoindre le dojo sur le',
      placeHolderLink: 'télégramme',
      link: 'https://t.me/ninja_org',
      isBlankTarget: true,
    },
  ],

  /*
  *
  * White Paper
  *
  * ******************************************************************************************* */
  WHITE_PAPER_H1: 'Anonyme-to-Peer prédiction change sur Ethereum',
  WHITE_PAPER_SUBTITLE_1: 'Salut ! Nous sommes le Roc, Bakunawa, Hakawai et Grootslang de l’équipe de Ninja. Nous construisons un échange électronique de prédiction sur la blockchain. Ici, c’est pourquoi nous l’avons fait, et comment il fonctionne !',
  WHITE_PAPER_SUBTITLE_2: 'Participez à la conversation à ',
  WHITE_PAPER_INTRO: 'Introduction',
  WHITE_PAPER_INTRO_1: 'Paris en ligne est exécuté presque exclusivement par les bookmakers qui servent de tiers de confiance. Comme c’est généralement le cas, les utilisateurs souffrent de ce « problème centralisé trente partie fiable » :',
  WHITE_PAPER_INTRO_2: [
    'Bookmakers définir les cotes qui sont toujours favorisent eux (ils gagnent toujours)',
    'Profitez de bookmakers un lourd 5 % — marge de 30 % sur chaque pari',
    'Les Paris sont réversibles, et gains restent incertains',
    'Complètement l’anonymat n’est pas possible',
    'La fraude est inévitable et admises reprocherai',
    'Point de défaillance unique — que se passe-t-il si le bookmaker disparaît ?',
    'Paris est considéré comme jeu — anormalement risqué, en grande partie en raison de la partie centralisée\'manque de s de transparence',
  ],
  WHITE_PAPER_INTRO_3: 'Ces problèmes se multiplient par 10 quand il vient à Paris en mode hors connexion, donc rien d’étonnant que les utilisateurs sont de plus en plus le moindre de deux maux.',
  WHITE_PAPER_INTRO_4_HIGH_LIGHT: 'La solution : un système de prévision électronique qui remplace la fiducie réticent avec preuve cryptographique, permettant aux deux parties anonymes de n’importe où dans le monde de parier directement contre eux sans la nécessité d’un tiers de confiance.',
  WHITE_PAPER_INTRO_5: 'Les Anonymous Peer-to-Peer échange électronique de prédiction (PEX) permet aux parties de parier directement contre l’autre sans passer par une autorité centrale ou le bookmaker. La gestion de Paris et au règlement des gains sont effectués collectivement par le réseau blockchain, protection des utilisateurs contre n’importe quel point de défaillance unique. PEX a des propriétés uniques qui permettent aux cas d’utilisation passionnant, auparavant impossibles sous n’importe quel mécanisme traditionnel de pari.',
  WHITE_PAPER_INTRO_6: 'Nous espérons que PEX changera la perception actuelle de Paris — souvent inutilement dépeint comme un jeu d’ombre, dû principalement à reliance centralisé parties recherchant des méthodes contraires à l’éthique, la truite fardées de faire du profit.',
  WHITE_PAPER_INTRO_7_HIGH_LIGHT: 'PEX défie directement l’industrie du jeu ombragée par un échange de marché ouvert et transparent de prédiction.',
  WHITE_PAPER_INTRO_8: 'Cet échange sera où les gens se rassemblent et prédire comme ils l’ont toujours fait, sur des événements futurs en sports, politique, science, marchés, climat et tout sous le soleil — en tant qu’individus qui investissent dans le monde que nous construisons naturellement Damián Ortega',
  WHITE_PAPER_PEX: 'Ce qui est PEX ?',
  WHITE_PAPER_PEX_1: 'En cours d’exécution sur le dessus de la blockchain de l’Ethereum, PEX est un échange anonyme-to-peer décentralisé prédiction qui offre un moyen simple pour tout le monde à :',
  WHITE_PAPER_PEX_2: [
    'Placez une Ordonnance alimentaire (Ask) ou Contre l’ordre (Bid) sur un résultat',
    'Être un Market Maker (les cotes) ou un Preneur de marché (les chances de retour)',
    'Être un créateur de leur propre Marché de prédiction',
    'Recueillir des gains instantanément (garanti par un Contrat Smart)',
  ],
  WHITE_PAPER_PEX_3: 'Placer un pari.',
  WHITE_PAPER_OUTCOME: 'Résultats en tant qu’actifs négociables. Chances que les prix.',
  WHITE_PAPER_OUTCOME_1: 'Dans une bourse, les actifs négociables, c’est partageret commerçants parier sur partager des prix unitaires (p. ex. vendre 100 actions de Apple à 200 dollars pièce).',
  WHITE_PAPER_OUTCOME_2: 'Dans un échange de pièce de monnaie, les actifs négociables est piceet commerçants parie sur les prix unitaires de pièce de monnaie (par exemple acheter 2 Bitcoin à 7000 $ chaque).',
  WHITE_PAPER_OUTCOME_3: 'De même, dans un échange décentralisé de prédire comme PEX, les actifs négociables est le résultat d’un événement, et commerçants de parier sur les chances de ce résultat. Ils peuvent parier pour le résultat (le supporte), ou parier contre elle. Par exemple : un résultat du match Brésil vs Espagne pourrait être que « le Brésil gagne ». John peut parier sur ce résultat avec des cotes de 2.0. Marie peut parier sur ces résultats dont les cotes sont de 2,25. Peter peut parier contre ce résultat (« Le Brésil perd » ou « Brésil attire ») dont les cotes sont de 1,9.',
  WHITE_PAPER_OUTCOME_4: 'A different type of exchange.',
  WHITE_PAPER_COMPARE: 'PEX vs traditionnel Paris',
  WHITE_PAPER_COMPARE_1: 'Surtout, PEX n’accepte pas les Paris et tenir des enjeux, mais correspond au lieu de cela les utilisateurs qui soutiennent les résultats avec les utilisateurs qui sont contre le résultat. Les enjeux sont détenus dans un contrat d’entiercement intelligent',
  WHITE_PAPER_COMPARE_2: 'L’entiercement contrat smart est imparable . Il fonctionne exactement comme programmé — de transmettre son équilibre de séquestre au gagnant à la fin — sans aucune possibilité d’interférence de temps d’arrêt, de fraude ou de tiers. Une fois que les deux parties s’engagent à un pari, c’est irréversible. Le paiement est garanti et instantané.',
  WHITE_PAPER_COMPARE_3: 'L’ensemble du processus passe sans n’importe quel groupe de révéler leur identité. Il est 100 % anonyme.',
  WHITE_PAPER_COMPARE_4: 'Tout cela passe sans une autorité centrale ou le bookmaker. Elle est réalisée collectivement par tous les nœuds de la blockchain.',
  WHITE_PAPER_COMPARE_5: 'This is why you should bet on the blockchain.',
  WHITE_PAPER_PEX_WORK: 'Comment fonctionne le PEX ?',
  WHITE_PAPER_PEX_WORK_SUB_TITLE: 'PEX est différent de ce que vous savez. Il fournit également une autonomie plus que ce que vous savez. Tout aussi important, il est conçu pour être facile à créer des marchés de pari et placer pari arrêtés.',
  WHITE_PAPER_STEP_1: 'Étape 1 : Get Ether',
  WHITE_PAPER_STEP_1_1: 'Si vous n’avez pas ETH encore, vous avez le choix entre acheter ETH directement en PEX avec votre carte de crédit. Vous pouvez également acheter ETH d’échanges de pièces populaires tels que Coinbase ou Binance.',
  WHITE_PAPER_STEP_1_2: 'PEX soutiendra les autres cryptocurrencies bientôt. PEX soutiendra les autres cryptocurrencies bientôt.',
  WHITE_PAPER_STEP_1_3: 'Facilement acheter ETH-app.',
  WHITE_PAPER_STEP_2: 'Étape 2 : Recharger votre portefeuille de PEX',
  WHITE_PAPER_STEP_2_1: 'Transférer les Eths, vous venez d’acheter dans le portefeuille de PEX, afin que vous puissiez commencer à placer des Paris avec vos ETH. Le portefeuille de PEX est complètement décentralisé. La clé privée est tenue sur votre téléphone et seulement vous pouvez y accéder. Seulement, vous pouvez transférer et recevoir ETH.',
  WHITE_PAPER_STEP_2_2: 'Le portefeuille PEX soigneusement organisé',
  WHITE_PAPER_STEP_3: 'Étape 3 : Placez un pari',
  WHITE_PAPER_STEP_3_1: 'Tout d’abord, choisissez un marché de prédiction qui vous intéresse (p. ex. Brésil — Espagne), le résultat (c\'est-à-dire "victoires Brésil"") et le côté (c\'est-à-dire soutenir ou parier contre le résultat).',
  WHITE_PAPER_STEP_3_2: 'Entrez ensuite le jeu que vous voulez à pari (c.-à-d. 1 ETH) et les cotes (c.-à-d. 1/2,25). L’enjeu sera mis dans un contrat d’entiercement intelligente. Le moteur de Matching PEX trouverez alors une autre ordonnance qui parie contre vents et marées que vous définir.',
  WHITE_PAPER_STEP_3_3: 'Voilà.',
  WHITE_PAPER_STEP_3_4: 'Notre ETH est en Argentine pour celui-ci.',
  WHITE_PAPER_STEP_4: 'Etape 4 : Attendez que le rapport',
  WHITE_PAPER_STEP_4_1: 'Une fois les extrémités de l’événement, le journaliste du marché relèvera le résultat dans la fenêtre de notification (fixé par le créateur du marché). En règle générale, vous attendez d’avoir le rapport quelques minutes. Si vous gagnez, vos gains seront automatiquement transférées du contrat escrow intelligente à votre compte.',
  WHITE_PAPER_STEP_4_2: 'May the odds be ever in your favour.',
  WHITE_PAPER_CREATE: 'Créez vos propres marchés de prédiction',
  WHITE_PAPER_CREATE_1: 'Alors que la plupart des utilisateurs vont passer des commandes sur des marchés existants, PEX permet à quiconque de créer un marché de prédiction sur toute activité future — que ce soit dans les sports, politique, science ou littéralement n’importe quel autre aspect de la vie moderne. Vous, comme le créateur de marché, pouvez régler les frais du marché, l\' heure de fermeture des marchés, le journaliste du résultatet le signalement de Date limite.',
  WHITE_PAPER_ARCHITECTURE: 'Architecture PEX',
  WHITE_PAPER_ARCHITECTURE_1: 'Les composants principaux de l’architecture PEX sont :',
  WHITE_PAPER_ARCHITECTURE_2_HL: 'Marché de prédiction',
  WHITE_PAPER_ARCHITECTURE_2: 'PEX permet à quiconque de créer un marché de prédiction sur toute activité future. Cela peut être dans n’importe quel champ — sports, politique, science, lifestyle, en même temps et ainsi de suite. La seule limite ici est votre créativité. Chaque marché fait partie d’un contrat intelligent sur chaîne . Il a son propre carnet d’ordres, les responsables et les preneurs.',
  WHITE_PAPER_ARCHITECTURE_3_HL: 'Carnet de commandes',
  WHITE_PAPER_ARCHITECTURE_3: 'Chaque marché de prédiction a son propre carnet de commandes. Carnet de commandes de PEX gère toutes les ordonnances résultat (demander) et tous contre résultats ordre (bid). Il regroupe toutes les commandes avec le même prix (cotes) dans une inscription sur le carnet de commandes.',
  WHITE_PAPER_ARCHITECTURE_3_1: 'The order book.',
  WHITE_PAPER_ARCHITECTURE_4_HL: 'Moteur correspondant',
  WHITE_PAPER_ARCHITECTURE_4_1: 'PEX utilise un carnet de commandes premier entré, premier sorti (FIFO). Les ordres sont exécutés en priorité prix-temps. Cela signifie qu’il correspondra par prix tout d’abord, et si il y a deux ordres avec le même prix, puis il correspondra par heure.',
  WHITE_PAPER_ARCHITECTURE_4_2: 'Dans certains cas, le montant placé sur chaque côté est inégal, et l’ordre sera partiellement rempli. L’ordre restant sera mis en correspondance avec le prochain prix-alors-chrono dans le carnet de commandes jusqu\'à ce que l’ordre est complètement rempli.',
  WHITE_PAPER_ARCHITECTURE_4_3: 'Votre match parfait.',
  WHITE_PAPER_ARCHITECTURE_4_4: [
    'Un utilisateur place une ordonnance issue de soutien dans le carnet d’ordres ouverts',
    'Un autre utilisateur passer une commande de résultat contre dans le carnet d’ordres ouverts',
    'Correspondance moteur trouve une correspondance et déplace les deux ordres du carnet de commandes ouvertes au carnet d’ordres appariés',
  ],
  WHITE_PAPER_ARCHITECTURE_5_HL: 'API REST',
  WHITE_PAPER_ARCHITECTURE_5: 'API REST PEX a des points de terminaison pour la gestion des commandes, gestion des comptes et données relatives au marché public.',
  WHITE_PAPER_ARCHITECTURE_6_HL: 'Web Socket',
  WHITE_PAPER_ARCHITECTURE_6: 'Flux de PEX Web Socket fournit boursières en temps réel mises à jour de données pour les commandes et les métiers.',
  WHITE_PAPER_PRIVACY: 'Confidentialité et anonymat',
  WHITE_PAPER_PRIVACY_SUB: 'L’intimité offerte à l’utilisateur est une création délibérée.',
  WHITE_PAPER_PRIVACY_1_HL: 'Aucun téléchargement',
  WHITE_PAPER_PRIVACY_1: 'PEX n’est pas une application mobile. Il est librement accessible sur le web mobile. Alors que les applications mobiles natives ont parfois mieux UI/UX, ils doivent être hébergés par les magasins app centralisé comme magasin de jeu Android ou Apple App store. À notre avis, une interface utilisateur plus attrayante n’est pas un compromis acceptable pour l’intimité compromise.',
  WHITE_PAPER_PRIVACY_2_HL: 'Aucun signe d’ups',
  WHITE_PAPER_PRIVACY_2_1: 'Le besoin d’un mot de passe, courriel ou numéro de téléphone est obsolète.',
  WHITE_PAPER_PRIVACY_2_2: 'PEX ne recueillir vos renseignements personnels. Vous pouvez utiliser PEX avec une intimité totale. Quand vous ouvrez d’abord PEX, une paire de clés publique/privée sera créé silencieusement en arrière-plan et stocké localement sur votre téléphone. La clé publique agit comme votre nom d’utilisateur anonyme, et la clé privée est votre mot de passe. PEX n’a pas accès à votre clé privée — seulement vous faire',
  WHITE_PAPER_PRIVACY_2_3: 'Notez que dans les paramètres du profil, nous fournissent une option pour l’utilisateur d’entrer son adresse email. Le but est pas de collecter votre adresse email, mais pour une meilleure expérience, surtout en cas liés aux paiements d’utilisation. Il est totalement facultatif.',
  WHITE_PAPER_PRIVACY_2_4: 'Notez également qu’il existe une option pour sauvegarder votre clé privée dans les paramètres. Nous vous recommandons de le faire.',
  WHITE_PAPER_PRIVACY_3_HL: 'Prédiction anonyme',
  WHITE_PAPER_PRIVACY_3: 'PEX est construit au sommet de l’Ethereum, qui est un blockchain public, mais la vie privée est maintenue en gardant votre clé publique anonyme. Alors que le public peut voir que quelqu\'un est prédire sur quelque chose, il est presque impossible de savoir que quelqu\'un whos.',
  WHITE_PAPER_PRIVACY_4_HL: 'Correspondance d’ordre anonyme',
  WHITE_PAPER_PRIVACY_4: 'Similaires aux échanges stocks et pièces de monnaie, le carnet de commandes, des tailles, cotes et temps sont publics, mais qui les décideurs de l’ordre et les preneurs sont ne dévoile pas le carnet de commandes. Les carnet de commandes documents parties anonyme pari placer contre l’autre, basé sur leurs prédictions défavorables d’un événement. Une fois que l’événement se termine et le rapport est disponible, les fonds entiercés sont transférés automatiquement au gagnant.',
  WHITE_PAPER_FEE: 'Frais',
  WHITE_PAPER_FEE_1: 'Il existe deux principaux types de frais : gagner la taxe et la redevance de réseau.',
  WHITE_PAPER_FEE_2: 'Les frais de gagnante est fixé par le créateur du marché, sous forme de pourcentage des gains totales de ce marché. Il appartient entièrement le créateur du marché pour définir leurs propres frais. Étant donné que PEX permet à quiconque de créer un marché de prédiction, nous attendons que les frais seront très compétitifs parmi les marchés. C’est le meilleur scénario pour les utilisateurs.',
  WHITE_PAPER_FEE_3: 'redevance de réseau est de 20 % des honoraires gagnante du créateur. Cela paie pour l’ingénierie, infrastructures et maintenance du réseau. Au début, cela se fera par l’équipe de Ninja de base. Mais Gageons qu’au fil du temps nous décentraliser l’équipe et concevoir un mécanisme qui ouvre jusqu\'à l’ensemble de la communauté.',
  WHITE_PAPER_FEE_4: 'En option, nous envisageons une redevance de saisine pour le créateur du marché. La piscine de renvoi pourrait être 10 % — 20 % de la taxe gagnante, qui contribuera à l’ajout d’utilisateurs beaucoup plus au marché.',
  WHITE_PAPER_SETTLEMENT: 'Settlement',
  WHITE_PAPER_SETTLEMENT_1: 'Le plus profond nous plonger dans le bâtiment PEX, plus il semble que nous devons atteindre initialement un compromis entre la vitesse et de la décentralisation, tout en conservant toujours la sécurité. En ce qui concerne le règlement, qui exige que le rapport des résultats soit disponible immédiatement après chaque événement (c\'est-à-dire une manifestation sportive), nous opterons pour la vitesse, pour l’instant.',
  WHITE_PAPER_SETTLEMENT_2: 'Dans la première version, l’équipe de Ninja de base assumera le rôle de rapports et le rapport le résultat de tous les événements. Nous sommes recherche et conception d’un mécanisme décentralisé qui permettra à la communauté de rendre compte des résultats.',
  WHITE_PAPER_SUMMARY: 'Résumé',
  WHITE_PAPER_SUMMARY_1: 'PEX est une version purement peer-to-peer de prédiction électronique permettant aux parties de parier directement entre eux sans passer par une autorité centrale ou le bookmaker. ',
  WHITE_PAPER_SUMMARY_2: 'PEX est open-source ; sa conception est publique, personne ne possède ou contrôle PEX et tout le monde peuvent prendre part. ',
  WHITE_PAPER_SUMMARY_3: 'PEX est open source à ',
  WHITE_PAPER_SUMMARY_4: 'PEX construire avec nous. Participez à la conversation au ',
  WHITE_PAPER_END: 'And it actually works',
  WHITE_PAPER_END_1: 'Hey, thanks for reading. Ninja will go live on the testnet on 5 June! We’re excited to hear your thoughts.',
};
